### ISSUE TITLE
Coordinating Julia version with system image version?

### ISSUE THREAD

**Issue by JackDunnNZ** [MichaelHatherly/SystemImageLoader.jl#22]
Thanks for a very interesting package! I am just exploring how it works, and was wondering if there was a way to ensure that the system image installed matches the Julia version. Consider:

```
$ julia +1.7
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.3 (2022-05-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.7) pkg> add https://github.com/MichaelHatherly/CuratedSystemImages.jl

julia> using CuratedSystemImages

julia> CuratedSystemImages.install()
Pick the system images you would like to install.
[press: d=done, a=all, n=none]
   [ ] AlgebraOfGraphics
 > [X] DataFrames
   [ ] JuliaFormatter
   [ ] JuliaSyntax
[ Info: installing `DataFrames` system image.
  Downloaded artifact: DataFrames
  Downloaded artifact: DataFrames
[ Info: finished installing `DataFrames` system image.

Add short names for selected images.
[press: d=done, a=all, n=none]
 > [X] DataFrames
[ Info: `juliaup` channel `1.7.3` already added, skipping.

julia> exit()

$ julia +DataFrames
ERROR: could not load library "/Users/jack/.julia/artifacts/caf82f4d14d28fb959b803f7823ce4731f93feea/environments/DataFrames/DataFrames.dylib"
dlopen(/Users/jack/.julia/artifacts/caf82f4d14d28fb959b803f7823ce4731f93feea/environments/DataFrames/DataFrames.dylib, 6): Symbol not found: _ijl_apply_generic
  Referenced from: /Users/jack/.julia/artifacts/caf82f4d14d28fb959b803f7823ce4731f93feea/environments/DataFrames/DataFrames.dylib
  Expected in: /Users/jack/.julia/juliaup/julia-1.7.3+0.x64/lib/julia/libjulia-internal.1.dylib
 in /Users/jack/.julia/artifacts/caf82f4d14d28fb959b803f7823ce4731f93feea/environments/DataFrames/DataFrames.dylib
```

As I understand how the package works, this is because the DataFrames sysimage was built for 1.8.1, but I was in 1.7.3 when I ran the install method, so it installed the image with that Julia channel.

In the [artifacts file](https://github.com/MichaelHatherly/CuratedSystemImages.jl/blob/b6963b5194e08049916db04fee912ded16e2fe95/Artifacts.toml) it looks like there is no reference to the Julia version, other than the fact that the URLs correspond to 1.8-latest. (as an aside I wonder there is a potential for a problem if the `-latest` version drifts between `juliaup` and the generated system images?)

I am wondering what the best way to ensure compatibility between the versions might be. Some possible options:
- specify the version in the artifact somehow and only install the system image if there exists a matching artifact for the current Julia version used to run the install
- install the system image for the Julia version corresponding to the system image, not the Julia version used to run the install (one drawback is that the long name of the channel might be hard to discover if you don't know the version of julia the system image was made with)
- prompt the user to select the system image to install, and then offer a choice of Julia versions for which there exist system images (defaulting to the current version being used if compatible)

Keen to hear your thoughts!

**Comment by MichaelHatherly** [comment]
Hi Jack, thanks for taking interest.

> and was wondering if there was a way to ensure that the system image installed matches the Julia version

Would be great if Julia itself would give a nicer error message when you try to do that rather than just saying `ERROR: could not load library`, which isn't great for new users.

If `Pkg.add` for git repo URLs handled `compat` then https://github.com/MichaelHatherly/CuratedSystemImages.jl/blob/main/Project.toml#L11 should solve the issue of only installing for the expected versions, but I'm pretty sure that requires the package to actually be registered to work correctly.

The simplest way to properly detect the used version and ensure that we have a usable Julia version is to check what the `Manifest.toml` associated with a particular system image has as it's `julia_version` field and then make sure to use that version for the `--julia=` flag to `system-image-loader`.

**Comment by MichaelHatherly** [comment]
https://github.com/MichaelHatherly/SystemImageLoader.jl/pull/23 should improve the handling of this somewhat.

**Comment by JackDunnNZ** [comment]
Thanks for your thoughts, I think #23 is a good solution for this. Looking forward to playing around with things a bit more!
